jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete old artifacts
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifacts = await github.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const weekAgo = new Date();
            weekAgo.setDate(weekAgo.getDate() - 7); // 7 days ago

            for (const artifact of artifacts.data.artifacts) {
              const artifactCreatedAt = new Date(artifact.created_at);
              if (artifactCreatedAt < weekAgo) {
                await github.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
                console.log(Deleted artifact: ${artifact.name});
              }
            }
